### ISSUE TITLE
golang client

### ISSUE THREAD

**Issue by carr123** [IceFireDB/IceFireDB#61]
hello, is there any golang client library that can talk to IceFireDB,  and can automatically do failover when one server node crashed ?

**Comment by gitsrc** [comment]
> hello, is there any golang client library that can talk to IceFireDB, and can automatically do failover when one server node crashed ?

You can use any SDK that supports the redis cluster mode to communicate with icefiredb. If a node in the icefiredb node group goes down, the icefiredb cluster will be automatically elected and restored.

**Comment by carr123** [comment]
@gitsrc thank you.   i know  icefiredb itself can suffer  one node crash. but some golang client don't.
when one server node is crashed, i expect the client can  automatically connect to other nodes.
as far as i know "https://github.com/mna/redisc" can not.

**Comment by gitsrc** [comment]
> @gitsrc thank you. i know icefiredb itself can suffer one node crash. but some golang client don't.
> when one server node is crashed, i expect the client can automatically connect to other nodes.
> as far as i know "https://github.com/mna/redisc" can not.

We have an icefiredb-proxy internally, which can help you shield all icefiredb cluster node status and metadata update issues after node downtime. It will make the access party’s SDK less difficult to use icefiredb. We can consider opening it later.

**Comment by carr123** [comment]
looking forward to it

**Comment by gitsrc** [comment]
> looking forward to it

https://github.com/IceFireDB/IceFireDB-Proxy，We are still enriching submissions.

**Comment by carr123** [comment]
@gitsrc thank you.  
and what's the benefits of IceFireDB-Proxy ?

**Comment by gitsrc** [comment]
> @gitsrc thank you.
> and what's the benefits of IceFireDB-Proxy ?

It can help you shield all icefiredb cluster node status and metadata update problems after node downtime.  It will reduce the difficulty of using icefiredb for the SDK of the visitor, and you can use icefiredb cluster like single-machine redis
