### ISSUE TITLE
Key Size limitation

### ISSUE THREAD

**Issue by rock59** [IceFireDB/IceFireDB#62]
LedisDb limits key size to 1024 bytes. Does this limitation apply to IceFireDB too?

**Comment by gitsrc** [comment]
> LedisDb limits key size to 1024 bytes. Does this limitation apply to IceFireDB too?

Yes, we have not adjusted this parameter.

**Comment by rock59** [comment]
Ledisdb can use rocksdb and leveldb as underlying storage engine. rocksdb and leveldb doesn't enforce such limitation for key size. It would be nice to redesign ledisdb to release the limitation of the key length.

**Comment by gitsrc** [comment]
> Ledisdb can use rocksdb and leveldb as underlying storage engine. rocksdb and leveldb doesn't enforce such limitation for key size. It would be nice to redesign ledisdb to release the limitation 

> Ledisdb can use rocksdb and leveldb as underlying storage engine. rocksdb and leveldb doesn't enforce such limitation for key size. It would be nice to redesign ledisdb to release the limitation of the key length.

Very good suggestion, we can add a configuration item to close this limit.
