### ISSUE TITLE
lua support

### ISSUE THREAD

**Issue by carr123** [IceFireDB/IceFireDB#63]
hello, do you hava plan to support lua script like traditional redis-server does ?
thanks.

**Comment by gitsrc** [comment]
> hello, do you hava plan to support lua script like traditional redis-server does ?
> thanks.

We did not use the lua mode, but the wasm mode, because wasm has better isolation and can also be combined with the subsequent ABI features of icefiredb.

**Comment by carr123** [comment]
@ how to use wasm in IceFireDB ?

**Comment by gitsrc** [comment]
> @ how to use wasm in IceFireDB ?

At present, the wasm part is not open source for the time being
