### ISSUE TITLE
Documentation to start up and query cluster?

### ISSUE THREAD

**Issue by lonnietc** [IceFireDB/IceFireDB#69]
Hello,

I was able to compile IceFireDB but have not found any documentation that shows the steps to start up a multi-node cluster and then make some queries?

I am interested in highly distributed P2P usage and scaling limits of IceFireDB
Thanks

**Comment by gitsrc** [comment]
Thank you for your attention. At present, p2p has just integrated the code of the beta version. We will also optimize the networking part for this version. At present, the documentation is lacking, and we will supplement the documentation in the future.

**Comment by lonnietc** [comment]
Thanks for getting back to me on this and I look forward to testing it out as the project that I have in mind would need to be able to scale to perhaps thousands of nodes in the cluster (some coming and going at different times).

Would be happy to test things out for you when you are ready.

**Comment by gitsrc** [comment]
Thank you very much, I will let you know as soon as possible.
