### ISSUE TITLE
是否支持在arm架构部署该项目

### ISSUE THREAD

**Issue by zhuangzhuang3** [IceFireDB/IceFireDB#784]
## Ask your question here
我这边在使用arm架构服务部署该项目的时候，执行make && ls ./bin/IceFireDB有报错
![image](https://github.com/user-attachments/assets/90dffef5-88b6-450d-af05-13b98e3ab797)

![image](https://github.com/user-attachments/assets/cd43fb45-d6bf-424d-bdc4-c92148f34c5e)

![image](https://github.com/user-attachments/assets/8b06ecfd-2d78-4bec-8703-b9d8ab433317)

**Comment by gitsrc** [comment]
@zhuangzhuang3  Thank you for your interest in IceFireDB's ARM support! I'm happy to confirm that we do support various ARM architectures. Our project's Makefile contains specific build targets for ARM64, ARMv5, ARMv6, and ARMv7.

You can find our Makefile here: [IceFireDB Makefile](https://github.com/IceFireDB/IceFireDB/blob/main/Makefile)

Here is a simple example of how to build IceFireDB for different ARM architectures using Makefile:

1. For ARM64:
```
make build-linux-arm64
```

2. For ARMv5, ARMv6, or ARMv7:
```
make build-linux-armv5
make build-linux-armv6
make build-linux-armv7
```

3. Build all ARM versions at once:
```
make all
```

After building, the corresponding binaries will be available in the `./bin/` directory.

**Comment by zhuangzhuang3** [comment]
makefile在arm上可以运行
